/*
 * Copyright (C) 2026 Tatar Keyboard contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rkr.simplekeyboard.inputmethod.latin.dictionary.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.BeforeClass
import org.junit.Test
import rkr.simplekeyboard.inputmethod.latin.dictionary.storage.DictionaryArtifactSpec
import rkr.simplekeyboard.inputmethod.latin.dictionary.storage.DictionaryTestFixtures
import rkr.simplekeyboard.inputmethod.latin.dictionary.storage.TdictValidator
import rkr.simplekeyboard.inputmethod.latin.suggestions.TatarSuffixRules
import java.io.File
import java.nio.ByteBuffer
import java.security.MessageDigest
import kotlin.math.ceil

/**
 * TT-TYPO-NEXT Phase B calibration (docs/TT-TYPO-NEXT-PLAN.md, gates written before measuring):
 *
 *  - G1 (recovery): recovery@3 on the regenerated class-#2 typo sets with the Tatar policy
 *    (classes #1+#2 + same-length bonus) must be >= 1.5x the class-#1-only baseline on its own
 *    set — on BOTH the 3-code-point window (the engine's MIN_FUZZY_PREFIX_CODE_POINTS, the
 *    conservative worst case) and the 5-code-point window (the "сцләм" case). The sets are
 *    regenerated by `scripts/typo_pack.py` with the device-true (gap-aware) geometry and pinned
 *    here by size and SHA-256, exactly like the E3a/E3b sets.
 *  - The E2E pin, measured BOTH ways: under the calibrated Phase-B candidate wiring (suffix
 *    rules + the {1,2}+bonus fuzzy policy + the layout-derived neighbour table) typing "сцләм"
 *    puts "сәләм" in cell 1 by the 5th letter (machinery proof); under the shipped DEFAULT wiring
 *    the strip stays empty — the gate verdict, not the machinery, decides what users get.
 *  - The Russian negative pin: the Russian engine keeps the default policy, so a Russian word
 *    reachable ONLY through a class-#2 edit ("спасибо" from "апаси", с→а) stays unreachable — and
 *    the same lookup under the TATAR policy recovers it, proving the pin discriminates.
 *
 * All metrics are printed as raw lines and the measured counts are pinned exactly (the
 * TtSuggestEvalTest discipline: any drift forces a conscious re-pin). The gate verdicts are
 * deliberately not tuned: if a gate fails, the TATAR policy stays unwired and the numbers stand
 * as the outcome (docs/TT-TYPO-NEXT.md).
 */
class TtTypoPhaseBCalibrationTest {

    // ---- Portable deterministic primitives (bit-identical to scripts/typo_pack.py). ----

    private fun fnv1a64(data: ByteArray): Long {
        var hash = 0xCBF29CE484222325uL.toLong()
        for (byte in data) {
            hash = hash xor (byte.toLong() and 0xffL)
            hash *= 0x100000001B3L
        }
        return hash
    }

    private fun splitmix64(seed: Long): Long {
        var z = seed + 0x9E3779B97F4A7C15uL.toLong()
        z = (z xor (z ushr 30)) * 0xBF58476D1CE4E5B9uL.toLong()
        z = (z xor (z ushr 27)) * 0x94D049BB133111EBuL.toLong()
        return z xor (z ushr 31)
    }

    private fun selectionIndex(word: String, choices: Int): Int =
        java.lang.Long.remainderUnsigned(
            splitmix64(SEED xor fnv1a64(word.toByteArray(Charsets.UTF_8))),
            choices.toLong(),
        ).toInt()

    // ---- Typo-set construction, mirroring scripts/typo_pack.py for the given class/window. ----

    private data class TypoRow(val word: String, val typoPrefixUtf8: ByteArray)
    private data class TypoSet(val rows: List<TypoRow>, val sha256: String)

    private fun buildSubstitutionSet(window: Int, geometric: Boolean): TypoSet {
        val rows = ArrayList<TypoRow>(vocabulary.size)
        val rendered = StringBuilder(vocabulary.size * 16)
        for (word in vocabulary) {
            val codePoints = word.codePoints().toArray()
            if (codePoints.size < window) continue
            val positions = ArrayList<Int>()
            val partners = ArrayList<Int>()
            for (position in 0 until window) {
                val neighbours =
                    if (geometric) {
                        neighborTable.geometricNeighborsOf(codePoints[position])
                    } else {
                        neighborTable.longPressPartnersOf(codePoints[position])
                    } ?: continue
                for (partner in neighbours) {
                    positions.add(position)
                    partners.add(partner)
                }
            }
            if (positions.isEmpty()) continue
            val choice = selectionIndex(word, positions.size)
            val typo = codePoints.copyOf(window)
            typo[positions[choice]] = partners[choice]
            val prefix = StringBuilder(window)
            for (slot in 0 until window) prefix.appendCodePoint(typo[slot])
            val prefixString = prefix.toString()
            rows.add(TypoRow(word, prefixString.toByteArray(Charsets.UTF_8)))
            rendered.append(word).append('\t').append(prefixString).append('\n')
        }
        val sha = MessageDigest.getInstance("SHA-256")
            .digest(rendered.toString().toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }
        return TypoSet(rows, sha)
    }

    @Test
    fun thePhaseBSetsAreByteIdenticalToTheGeneratorRuns() {
        // Identities of `python3 scripts/typo_pack.py build --edit-class {1,2}
        // [--prefix-code-points 5]` on the committed 110k asset with the device-true geometry.
        val class1w3 = buildSubstitutionSet(3, geometric = false)
        assertEquals(96_118, class1w3.rows.size)
        assertEquals("1bf09f403a288c111a1607c83eecee3faa410ee5669015b558e292cbe28e9aee", class1w3.sha256)
        val class1w5 = buildSubstitutionSet(5, geometric = false)
        assertEquals(102_478, class1w5.rows.size)
        assertEquals("1c0bd7e7cbf523306e69214d05fd0833022d5322143a1f435a8c4f8ce7f953c6", class1w5.sha256)
        val class2w3 = buildSubstitutionSet(3, geometric = true)
        assertEquals(109_649, class2w3.rows.size)
        assertEquals("f64f46506ec5c0be19aabc496b11da5c3ca9d875631dc25c6e1d511a87dce9d3", class2w3.sha256)
        val class2w5 = buildSubstitutionSet(5, geometric = true)
        assertEquals(104_955, class2w5.rows.size)
        assertEquals("165dbaac09b47d333c5abb10a9e5df47d32671613f023747b3f4933258142d0f", class2w5.sha256)
    }

    @Test
    fun gateG1RecoveryAtThreeOnBothWindows() {
        val baseline = requireNotNull(defaultIndex)
        val tatar = requireNotNull(tatarIndex)
        val noBonus = requireNotNull(tatarNoBonusIndex)
        val class1w3 = buildSubstitutionSet(3, geometric = false)
        val class1w5 = buildSubstitutionSet(5, geometric = false)
        val class2w3 = buildSubstitutionSet(3, geometric = true)
        val class2w5 = buildSubstitutionSet(5, geometric = true)

        // Baseline: the pre-Phase-B configuration (FuzzyEditPolicy.DEFAULT — class #1 only, no
        // bonus) on its own class #1 sets, one per window.
        val baseW3 = measureRecovery(baseline, class1w3)
        val baseW5 = measureRecovery(baseline, class1w5)
        // Candidate: the Tatar wiring (classes #1+#2 + bonus) on the class #2 sets.
        val candW3 = measureRecovery(tatar, class2w3)
        val candW5 = measureRecovery(tatar, class2w5)
        // Attribution: the same two classes WITHOUT the same-length bonus.
        val noBonusW3 = measureRecovery(noBonus, class2w3)
        val noBonusW5 = measureRecovery(noBonus, class2w5)

        // The gate compares RATES (recovery@3 is a percentage), not raw counts — the two sets
        // differ in size.
        val ratioW3 = candW3.rate / baseW3.rate
        val ratioW5 = candW5.rate / baseW5.rate

        // Raw calibration lines (grep target: "PhaseB recovery@3").
        println(
            "PhaseB recovery@3 window=3cp baseline(class1-only, class1 set)=" +
                "${fmt(baseW3.rate)}% (${baseW3.recovered}/${baseW3.total}) " +
                "tatarPolicy(classes1+2+bonus, class2 set)=${fmt(candW3.rate)}% (${candW3.recovered}/${candW3.total}) " +
                "ratio=${fmt(ratioW3)}x gate>=1.5x verdict=${if (ratioW3 >= 1.5) "PASS" else "BELOW"} " +
                "noBonus=${fmt(noBonusW3.rate)}% (${noBonusW3.recovered}) " +
                "variant_p95=${candW3.variantP95} variant_max=${candW3.variantMax} " +
                "visited_p95=${candW3.visitedP95} visited_max=${candW3.visitedMax} over_budget=${candW3.overBudget}",
        )
        println(
            "PhaseB recovery@3 window=5cp baseline(class1-only, class1 set)=" +
                "${fmt(baseW5.rate)}% (${baseW5.recovered}/${baseW5.total}) " +
                "tatarPolicy(classes1+2+bonus, class2 set)=${fmt(candW5.rate)}% (${candW5.recovered}/${candW5.total}) " +
                "ratio=${fmt(ratioW5)}x gate>=1.5x verdict=${if (ratioW5 >= 1.5) "PASS" else "BELOW"} " +
                "noBonus=${fmt(noBonusW5.rate)}% (${noBonusW5.recovered}) " +
                "variant_p95=${candW5.variantP95} variant_max=${candW5.variantMax} " +
                "visited_p95=${candW5.visitedP95} visited_max=${candW5.visitedMax} over_budget=${candW5.overBudget}",
        )

        // Exact pins of the measured counts (re-pin consciously when an input changes).
        assertEquals("the fuzzy budget must never trip", 0, candW3.overBudget)
        assertEquals("the fuzzy budget must never trip", 0, candW5.overBudget)
        assertEquals(PIN_BASE_W3, baseW3.recovered)
        assertEquals(PIN_BASE_W5, baseW5.recovered)
        assertEquals(PIN_CAND_W3, candW3.recovered)
        assertEquals(PIN_CAND_W5, candW5.recovered)
        assertEquals(PIN_NOBONUS_W3, noBonusW3.recovered)
        assertEquals(PIN_NOBONUS_W5, noBonusW5.recovered)
    }

    private data class Measurement(
        val total: Int,
        val recovered: Int,
        val variantP95: Int,
        val variantMax: Int,
        val visitedP95: Int,
        val visitedMax: Int,
        val overBudget: Int,
    ) {
        val rate: Double get() = recovered * 100.0 / total
    }

    private fun measureRecovery(index: TdictPrefixIndex, set: TypoSet): Measurement {
        val variantCounts = ArrayList<Int>()
        val visitedCounts = ArrayList<Int>()
        var overBudget = 0
        var recovered = 0
        for (row in set.rows) {
            val results = index.lookup(ImmutableUtf8Prefix.copyOf(row.typoPrefixUtf8))
            if (index.lastFuzzyVariantCount > 0 || index.lastFuzzyVisitedCount > 0) {
                variantCounts.add(index.lastFuzzyVariantCount)
                visitedCounts.add(index.lastFuzzyVisitedCount)
            }
            if (index.lastFuzzyOverBudget) overBudget++
            if (results.contains(row.word)) recovered++
        }
        return Measurement(
            set.rows.size, recovered,
            percentile(variantCounts.sorted(), 0.95), variantCounts.maxOrNull() ?: 0,
            percentile(visitedCounts.sorted(), 0.95), visitedCounts.maxOrNull() ?: 0,
            overBudget,
        )
    }

    /**
     * The Phase-B target case, end to end on the real asset under the CALIBRATED CANDIDATE wiring
     * (suffix rules + the {1,2}+bonus fuzzy policy + the layout-derived neighbour table): "сцләм"
     * (ц for ә — a cross-row geometric pair that survives on device) offers "сәләм" in cell 1 by
     * the 5th letter. This is the machinery proof for the record: gate G1 measured below
     * threshold, so this configuration is NOT shipped — [theShippedEnginesKeepThePrePhaseBBehavior]
     * pins what users actually get. (Phase C re-measures the same case under the {1,4} probe-first
     * candidate in TtTypoPhaseCCalibrationTest.)
     */
    @Test
    fun theSclamTypoOffersSyalamInCellOneByTheFifthLetter() {
        val index = requireNotNull(tatarIndex)
        fun strip(prefix: String): List<String> =
            index.lookup(ImmutableUtf8Prefix.copyOf(prefix.toByteArray(Charsets.UTF_8)))

        // 2 code points: the fuzzy pass never fires (MIN_FUZZY_PREFIX_CODE_POINTS = 3); the strip
        // is the exact "сц*" block (сценарий & co., frequency order).
        assertEquals(listOf("сценарий", "сценарие", "сценарийлар"), strip("сц"))
        // 3 code points: exact "сцл*" is empty; the class-#2 variant "сәл" fills the strip by
        // frequency (no same-length candidate exists at 3 cp, and the huge "сәл*" block leads).
        assertEquals(listOf("сәламәтлек", "сәләтле", "сәламәт"), strip("сцл"))
        // 4 code points: the variant "сәлә" covers the "сәлә*" block, whose frequency leaders are
        // the "сәләт*" words — the correction itself (freq 36) does not reach the strip yet.
        assertEquals(listOf("сәләтле", "сәләт", "сәләтен"), strip("сцлә"))
        // 5 code points: the variant "сәләм" selects exactly the "сәләм*" block, and the
        // same-length bonus puts the correction itself (36) above "сәләмәтлек" (65).
        assertEquals(listOf("сәләм", "сәләмәтлек", "сәләмәт"), strip("сцләм"))
    }

    /**
     * The DEFAULT policy keeps the pre-Phase-B behavior (class #1 only, no bonus) — this is what
     * the Russian engine ships and what any engine opened without a policy runs. (The Tatar
     * engine's shipped behavior changed in Phase C2: it now runs [FuzzyEditPolicy.TATAR], and
     * "сцләм" offers "сәләм" — pinned in TtTypoPhaseCCalibrationTest.) "сцләм" under DEFAULT:
     * empty strip — с and ц have no long-press partner, so class #1 generates nothing here.
     */
    @Test
    fun theDefaultPolicyKeepsThePrePhaseBBehavior() {
        val index = requireNotNull(defaultIndex)
        fun strip(prefix: String): List<String> =
            index.lookup(ImmutableUtf8Prefix.copyOf(prefix.toByteArray(Charsets.UTF_8)))
        assertEquals(listOf("сценарий", "сценарие", "сценарийлар"), strip("сц"))
        assertEquals(emptyList<String>(), strip("сцл"))
        assertEquals(emptyList<String>(), strip("сцлә"))
        assertEquals(emptyList<String>(), strip("сцләм"))
    }

    /**
     * The Russian engine keeps the default policy: a word reachable ONLY through a class-#2 edit
     * stays unreachable. "апаси" (а for с on "спаси(бо)") has zero exact continuations in the
     * Russian asset and no class-#1 path (с has no long-press partner), so the strip stays empty —
     * while the SAME dictionary under the Phase-B candidate policy recovers "спасибо", proving
     * the pin is not vacuous.
     */
    @Test
    fun theRussianEngineIsUntouchedByClass2() {
        val russianDefault = requireNotNull(russianDefaultIndex)
        val russianAsTatar = requireNotNull(russianTatarPolicyIndex)
        val typo = ImmutableUtf8Prefix.copyOf("апаси".toByteArray(Charsets.UTF_8))
        val defaultResult = russianDefault.lookup(typo)
        assertFalse("class #2 must stay off the default (Russian) path", defaultResult.contains("спасибо"))
        assertEquals(emptyList<String>(), defaultResult)
        val tatarPolicyResult = russianAsTatar.lookup(typo)
        assertTrue(
            "premise: the case discriminates — the Phase-B candidate policy recovers it",
            tatarPolicyResult.contains("спасибо"),
        )
    }

    /**
     * G3 (host): lookup latency with class #2 engaged, measured on a deterministic sample of the
     * class-#2 5-cp typo set — exactly the workload Phase B adds. The same measurement on the
     * DEFAULT policy is the before/after control. The 5 ms p95 assertion matches the long-standing
     * D1d budget of [RealDictionaryPrefixIndexTest].
     */
    @Test
    fun gateG3HostComputeP95WithClass2Engaged() {
        val class2w5 = buildSubstitutionSet(5, geometric = true)
        // Deterministic sample of the set: every 53rd row (~2 000 prefixes).
        val sample = class2w5.rows.filterIndexed { index, _ -> index % 53 == 0 }
            .map { ImmutableUtf8Prefix.copyOf(it.typoPrefixUtf8) }
        assertTrue("the perf sample is meaningful", sample.size > 1_500)

        val arms = listOf(
            "default" to requireNotNull(defaultIndex),
            "tatarPolicy" to requireNotNull(tatarIndex),
        )
        for ((name, index) in arms) {
            repeat(2) { for (prefix in sample) index.lookup(prefix) }
            val timings = LongArray(sample.size * 2)
            var consumed = 0
            var at = 0
            repeat(2) {
                for (prefix in sample) {
                    val started = System.nanoTime()
                    val results = index.lookup(prefix)
                    timings[at++] = System.nanoTime() - started
                    consumed = consumed xor results.size
                }
            }
            timings.sort()
            val p50 = timings[timings.size / 2] / 1_000_000.0
            val p95 = timings[ceil(timings.size * 0.95).toInt() - 1] / 1_000_000.0
            val max = timings.last() / 1_000_000.0
            // Raw calibration line (grep target: "PhaseB perf").
            println(
                "PhaseB perf host window=5cp policy=$name samples=${timings.size} " +
                    "p50=${fmtMs(p50)} ms p95=${fmtMs(p95)} ms max=${fmtMs(max)} ms consumed=$consumed",
            )
            if (name == "tatarPolicy") {
                assertTrue("class-#2-engaged p95=${p95}ms exceeds the 5 ms budget", p95 <= 5.0)
            }
        }
    }

    private fun fmtMs(value: Double): String = "%.3f".format(java.util.Locale.ROOT, value)

    private fun percentile(sorted: List<Int>, fraction: Double): Int {
        if (sorted.isEmpty()) return 0
        val rank = maxOf(1, ceil(sorted.size * fraction).toInt())
        return sorted[rank - 1]
    }

    private fun fmt(value: Double): String = "%.4f".format(java.util.Locale.ROOT, value)

    companion object {
        private const val SEED = 20260727L

        // Exact pins of the G1 measurement (2026-09-20, committed 110k asset, device-true
        // geometry); re-pin consciously when an input changes. The verdict was BELOW on both
        // windows (ratios of RATES 0.9090x / 1.0019x vs the 1.5x gate), so the TATAR policy stays
        // unwired.
        private const val PIN_BASE_W3 = 6_436
        private const val PIN_BASE_W5 = 39_344
        private const val PIN_CAND_W3 = 6_674
        private const val PIN_CAND_W5 = 40_370
        private const val PIN_NOBONUS_W3 = 6_673
        private const val PIN_NOBONUS_W5 = 40_379

        private val neighborTable = E3bTestFixtures.tatarNeighborTable()
        private lateinit var vocabulary: List<String>
        private var defaultIndex: TdictPrefixIndex? = null
        private var tatarIndex: TdictPrefixIndex? = null
        private var tatarNoBonusIndex: TdictPrefixIndex? = null
        private var russianDefaultIndex: TdictPrefixIndex? = null
        private var russianTatarPolicyIndex: TdictPrefixIndex? = null

        // The Phase-B measured arm: classes #1+#2 + the same-length bonus — FuzzyEditPolicy.TATAR
        // as calibrated in Phase B. Phase C redefined TATAR to the {1,4} probe-first candidate, so
        // this arm is spelled out explicitly and the pinned Phase-B numbers stay comparable.
        private val PHASE_B_CANDIDATE = FuzzyEditPolicy(
            intArrayOf(TdictPrefixIndex.EDIT_CLASS_LONG_PRESS, TdictPrefixIndex.EDIT_CLASS_GEOMETRIC),
            true,
        )

        // The two shipped classes without the bonus — the attribution arm of G1.
        private val TATAR_NO_BONUS = FuzzyEditPolicy(
            intArrayOf(TdictPrefixIndex.EDIT_CLASS_LONG_PRESS, TdictPrefixIndex.EDIT_CLASS_GEOMETRIC),
            false,
        )

        @JvmStatic
        @BeforeClass
        fun loadCommittedDictionaries() {
            val tatarRaw = inflate(DictionaryArtifactSpec.TATAR_TOP100K_V1)
            vocabulary = DictionaryTestFixtures.words(tatarRaw)
            check(vocabulary.size == DictionaryArtifactSpec.TATAR_TOP100K_V1.expectedEntryCount.toInt())
            // The production Tatar shape: P3 suffix rules + the Phase-B fuzzy policy. The baseline
            // and the no-bonus attribution index carry the suffix rules too, so only the fuzzy
            // policy differs between the arms.
            defaultIndex = openIndex(tatarRaw, DictionaryArtifactSpec.TATAR_TOP100K_V1, TatarSuffixRules, null)
            tatarIndex = openIndex(tatarRaw, DictionaryArtifactSpec.TATAR_TOP100K_V1, TatarSuffixRules, PHASE_B_CANDIDATE)
            tatarNoBonusIndex = openIndex(tatarRaw, DictionaryArtifactSpec.TATAR_TOP100K_V1, TatarSuffixRules, TATAR_NO_BONUS)
            for (index in listOfNotNull(defaultIndex, tatarIndex, tatarNoBonusIndex)) {
                index.updateKeyNeighbors(neighborTable)
            }

            val russianRaw = inflate(DictionaryArtifactSpec.RUSSIAN_TOP100K_V1)
            russianDefaultIndex = openIndex(russianRaw, DictionaryArtifactSpec.RUSSIAN_TOP100K_V1, null, null)
            russianTatarPolicyIndex = openIndex(russianRaw, DictionaryArtifactSpec.RUSSIAN_TOP100K_V1, null, PHASE_B_CANDIDATE)
            for (index in listOfNotNull(russianDefaultIndex, russianTatarPolicyIndex)) {
                index.updateKeyNeighbors(neighborTable)
            }
        }

        /** Inflates and validates a committed asset exactly like the other real-asset tests. */
        private fun inflate(spec: DictionaryArtifactSpec): ByteArray {
            val asset = locate(
                "src/main/assets/${spec.assetPath}",
                "app/src/main/assets/${spec.assetPath}",
            )
            val rawFile = File.createTempFile("tt-typo-b-", ".tdict")
            try {
                rawFile.outputStream().use { output ->
                    TdictValidator().inflateAsset(asset.inputStream(), output, spec)
                }
                TdictValidator().validateRaw(rawFile, spec)
                return rawFile.readBytes()
            } finally {
                rawFile.delete()
            }
        }

        private fun openIndex(
            raw: ByteArray,
            spec: DictionaryArtifactSpec,
            suffixTable: InflectedSuffixTable?,
            policy: FuzzyEditPolicy?,
        ): TdictPrefixIndex {
            val identity = DictionaryIdentity(
                spec.generation,
                spec.schemaId,
                spec.formatVersion,
                MessageDigest.getInstance("SHA-256").digest(raw).joinToString("") { "%02x".format(it) },
            )
            return requireNotNull(
                TdictPrefixIndex.open(
                    ByteBuffer.wrap(raw), identity,
                    spec.expectedEntryCount, raw.size.toLong(), suffixTable, policy,
                ),
            )
        }

        private fun locate(vararg paths: String): File =
            paths.map(::File).firstOrNull(File::isFile)
                ?: error("cannot locate committed dictionary test resource")
    }
}
