/*
 * Copyright (C) 2026 Tatar Keyboard contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package rkr.simplekeyboard.inputmethod.latin.suggestions

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import rkr.simplekeyboard.inputmethod.latin.dictionary.engine.EngineTestFixtures
import rkr.simplekeyboard.inputmethod.latin.dictionary.engine.ImmutableUtf8Prefix

/**
 * P3 after-word forms (docs/TT-SUGGESTIONS.md): generated inflections of the committed word,
 * filtered to dictionary words and ranked by frequency. Driven against a real [TdictPrefixIndex]
 * over a fixture dictionary, so the generation -> presence-filter -> ranking pipeline is exercised
 * exactly as the engine runs it.
 */
class TatarAfterWordFormsTest {

    // Sorted by code point, as the fixture format requires. The татар family carries the canonical
    // frequencies of the shipped dictionary; китап variants pin the voicing simplification
    // (китапы is generated but absent — the dictionary carries китабы, which is not generated).
    private val entries = listOf(
        "китабы" to 9_000L,
        "китап" to 50_000L,
        "китапка" to 3_000L,
        "татар" to 134_412L,
        "татарга" to 1_325L,
        "татарлар" to 12_085L,
        "татарның" to 2_752L,
        "татарча" to 9_093L,
        "эшләгән" to 500L,
    )

    private fun forms(): AfterWordFormsForTest = AfterWordFormsForTest()

    private inner class AfterWordFormsForTest {
        val index = EngineTestFixtures.index(entries)
        val provider = TatarSuffixRules.createAfterWordForms(index)

        fun of(word: String, alreadyShown: List<String> = emptyList(), maxOut: Int = 3) =
            provider.formsOf(
                ImmutableUtf8Prefix.copyOf(word.toByteArray(Charsets.UTF_8)),
                alreadyShown, maxOut,
            )
    }

    @Test
    fun formsOfACommittedWordAreDictionaryInflectionsRankedByFrequency() {
        val result = forms().of("татар")
        // татарлар (12 085) and татарча (9 093) lead; татарның (2 752) follows, татарга (1 325)
        // is cut by maxOut. Generated-but-absent forms (татары, татара, татарды, …) never appear.
        assertEquals(listOf("татарлар", "татарча", "татарның"), result)
    }

    @Test
    fun generatedButAbsentFormsAreFilteredOut() {
        val result = forms().of("китап")
        // китапка is in the fixture; китапы (the un-voiced 3sg possessive the runtime rules
        // generate) is not — and китабы, the real form, is not generated by the runtime rules at
        // all (the P1 voicing exceptions are deliberately not replicated, documented in
        // TatarSuffixRules), so neither appears.
        assertEquals(listOf("китапка"), result)
    }

    @Test
    fun formsNeverRepeatTheBigramSuccessorsOrTheWordItself() {
        // татарча already shown by the bigrams: it drops out and the next attested form
        // (татарга, 1 325) backfills the third slot.
        val result = forms().of("татар", alreadyShown = listOf("татарча"))
        assertEquals(listOf("татарлар", "татарның", "татарга"), result)
        assertTrue(forms().of("татар").none { it == "татар" })
    }

    @Test
    fun theOutputIsCappedAtMaxOut() {
        assertEquals(1, forms().of("татар", maxOut = 1).size)
        assertEquals(2, forms().of("татар", maxOut = 2).size)
        assertTrue(forms().of("татар", maxOut = 0).isEmpty())
    }

    @Test
    fun aWordWithoutAttestedFormsOffersNothing() {
        // эшләгән has no generated-form continuation in the fixture, and is itself not a stem the
        // rules extend into a fixture word.
        assertTrue(forms().of("эшләгән").isEmpty())
        // A Russian word on the Tatar slot: harmony applies, but nothing generated is a fixture
        // word — the dictionary filter is the fail-closed gate.
        assertTrue(forms().of("привет").isEmpty())
    }

    @Test
    fun invalidInputIsRejectedClosed() {
        val f = forms()
        assertTrue(f.of("").isEmpty())
        val invalid = byteArrayOf(0xC0.toByte(), 0xAF.toByte()) // overlong, not a scalar
        assertTrue(
            f.provider.formsOf(ImmutableUtf8Prefix.copyOf(invalid), emptyList(), 3).isEmpty(),
        )
    }
}
